services:
  - type: web
    name: virscale-ai
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    dockerBuildContext: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      # Add your API keys as environment variables in Render dashboard
      # Don't put secrets in this file!
    healthCheckPath: /
    autoDeploy: true