#:schema node_modules/wrangler/config-schema.json
name = "virscale"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[build]
command = "pnpm install && pnpm run build"
